name: 🚀 Run release-please
on:
  push:
    branches:
      - develop
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: go
          target-branch: develop
